import turtle
ob = turtle.Turtle()
ob.color("red")
ob.forward(100)
ob.color("green")
ob.left(90)
ob.forward(100)
ob.color("orange")
ob.left(90)
ob.forward(100)
ob.color("yellow")
ob.left(90)
ob.forward(100)
turtle.done()